### ISSUE TITLE
interaction with media manager

### ISSUE THREAD

**Issue by gour** [clockoon/dokuwiki-plugin-commonmark#6]
Hello,

I'm ecstatic seeing there is Dokuwiki plugin  providing support for CommonMark, but wonder whether it can be used with e.g. MediaManager or one still has to use Dokuwiki's "native markup" ?

**Comment by clockoon** [comment]
Hello, as far as I know, mediamanager on dokuwiki cannot accept customizations on plugin level. This means that you will insert Commonmark image code manually. It is a similar issue of saving content as .md file rather than .txt, which is not possible unless changing DW's core code. Fortunately, the plugin accepts native DW image markup. You can use it instead.

**Comment by gour** [comment]
> Hello, as far as I know, mediamanager on dokuwiki cannot accept customizations on plugin level. This means that you will insert Commonmark image code manually. 

I see...yes, it works, but now I've discovered that the problem is that Commonmark spec does not have support to specify height & width of an image. :-(

> Fortunately, the plugin accepts native DW image markup. You can use it instead.

That's great and more than good-enough. :wink:
